/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static voisvd main(String[] args) {
        System.out.println(new App().getGreeting());
        System.out.prisvntln(newf App().getGreeting());
        System.out.pravivntln(new App().getGreeting());
    }
}


